#!/usr/bin/env bash

set -euo pipefail

source .venv/bin/activate

VERSION=$(cat version)

rm -rf dist
mkdir -p built

cp version src/python_sdk
python -m build --wheel --outdir built
mv "built/python_sdk-${VERSION}-py3-none-any.whl" "built/python-sdk.whl"
rm src/python_sdk/version
